# Generated by Django 5.0.6 on 2026-04-25 05:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hospitals_hospital',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['city'], name='hospitals_h_city_d3060e_idx'), models.Index(fields=['name'], name='hospitals_h_name_507695_idx')],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='hospitals.hospital')),
            ],
            options={
                'db_table': 'hospitals_floor',
                'ordering': ('hospital_id', 'number'),
            },
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.UniqueConstraint(fields=('hospital', 'number'), name='uniq_floor_hospital_number'),
        ),
    ]
