# Generated by Django 5.0.6 on 2026-04-25 05:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=10)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('has_window', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('qr_code_token', models.CharField(max_length=64, unique=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hospitals.floor')),
            ],
            options={
                'db_table': 'rooms_room',
                'ordering': ('floor_id', 'number'),
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('is_near_window', models.BooleanField(default=False)),
                ('current_status', models.CharField(choices=[('BAND', 'Band'), ('BOSH', "Bo'sh"), ('NOMALUM', "Noma'lum")], default='NOMALUM', max_length=10)),
                ('last_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_count', models.PositiveIntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='rooms.room')),
            ],
            options={
                'db_table': 'rooms_bed',
                'ordering': ('room_id', 'position'),
            },
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['qr_code_token'], name='rooms_room_qr_code_400a10_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('floor', 'number'), name='uniq_room_floor_number'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['current_status'], name='rooms_bed_current_5fda3f_idx'),
        ),
        migrations.AddConstraint(
            model_name='bed',
            constraint=models.UniqueConstraint(fields=('room', 'position'), name='uniq_bed_room_position'),
        ),
    ]
