release: python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py seed
web: gunicorn shifo_radar.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 60 --access-logfile -
