# Generated by Django 5.0.6 on 2026-04-25 05:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_reported', models.CharField(choices=[('BAND', 'Band'), ('BOSH', "Bo'sh"), ('NOMALUM', "Noma'lum")], max_length=10)),
                ('confirmation_type', models.CharField(choices=[('SELF', 'Meniki'), ('NEIGHBOR', "Qo'shni")], max_length=10)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, default='', max_length=45)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('oneid_session_id', models.CharField(blank=True, default='', max_length=64)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='rooms.bed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'confirmations_confirmation',
                'ordering': ('-confirmed_at',),
                'indexes': [models.Index(fields=['bed', '-confirmed_at'], name='idx_conf_bed_time'), models.Index(fields=['user', '-confirmed_at'], name='idx_conf_user_time')],
            },
        ),
    ]
